---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: hello
  image: busybox
  environment:
   SECRET:
    from_secret: secretv
  commands:
  - echo $SECRET
  - echo "Test"
- name: start-notify
  image: plugins/slack
  settings:
    webhook: 
      from_secret: slack_webhook
    channel: developers
    template: >
        Build {{build.number}} of {{build.branch}} started. {{build.link}}
trigger:
event:
- refs/tags/*
