---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: hello
  image: busybox
  environment:
   SECRET:
    from_secret: secretv
  commands:
  - echo $SECRET
  - echo "Test"
- name: start-notify
  image: plugins/slack
  settings:
    webhook: https://hooks.slack.com/services/T05U1PZGMC2/B05UEDJQX33/$SECRET
    channel: developers
    template: >
        Build {{build.number}} of {{build.branch}} started. {{build.link}}
trigger:
  branch:
  - main
