---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: hello
  image: busybox
  environment:
   SECRET:
    from_secret: secretv
  commands:
  - echo $SECRET
  - echo "Test"
- name: start-notify
  image: plugins/slack
  settings:
    webhook: 
      from_secret: slack_webhook
    channel: developers
    template: >
      {{#success build.status}}
        build - {{repo.name}} - {{build.number}} succeeded. Tag Created by {{build.author}} link {{build.link}} date: {{build.created}}
      {{else}}
        build  {{repo.name}} - {{build.number}} failed. Tagiing attemp by {{build.author}}  Fix me please. <@channelnam> <@someone>
      {{/success}}
  when:
    ref:
    - refs/tags/*
