---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: hello
  image: busybox
  commands:
  - echo $secretv
- name: start-notify
  image: plugins/slack
  settings:
    webhook: https://hooks.slack.com/services/T05U1PZGMC2/B05UEDJQX33/$secretv
    channel: developers
    template: >
        Build {{build.number}} of {{build.branch}} started. {{build.link}}
trigger:
  branch:
  - main
