---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: hello
  image: busybox
  environment:
   SECRET:
    from_secret: secretv
  commands:
  - echo $SECRET
  - echo "Test"
- name: start-notify
  image: plugins/slack
  settings:
    webhook: 
      from_secret: slack_webhook
    channel: developers
    template: >
      {{#success build.status}}
        Repo: {{repo.name}}, build #: {{build.number}} succeeded. Tag: {{build.tag}} created by user: {{build.author}}. Reference link {{build.link}} 
      {{else}}
        Repo: {{repo.name}}, build #: {{build.number}} failed. Tagging attemp by {{build.author}}  Fix me please. <@channelnam> <@someone>
      {{/success}}
  when:
    ref:
    - refs/tags/*
